/* automatically generated by rust-bindgen 0.72.0 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::core::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const VIRTIO_CONFIG_S_ACKNOWLEDGE: u32 = 1;
pub const VIRTIO_CONFIG_S_DRIVER: u32 = 2;
pub const VIRTIO_CONFIG_S_DRIVER_OK: u32 = 4;
pub const VIRTIO_CONFIG_S_FEATURES_OK: u32 = 8;
pub const VIRTIO_CONFIG_S_NEEDS_RESET: u32 = 64;
pub const VIRTIO_CONFIG_S_FAILED: u32 = 128;
pub const VIRTIO_TRANSPORT_F_START: u32 = 28;
pub const VIRTIO_TRANSPORT_F_END: u32 = 42;
pub const VIRTIO_F_NOTIFY_ON_EMPTY: u32 = 24;
pub const VIRTIO_F_ANY_LAYOUT: u32 = 27;
pub const VIRTIO_F_VERSION_1: u32 = 32;
pub const VIRTIO_F_ACCESS_PLATFORM: u32 = 33;
pub const VIRTIO_F_IOMMU_PLATFORM: u32 = 33;
pub const VIRTIO_F_RING_PACKED: u32 = 34;
pub const VIRTIO_F_IN_ORDER: u32 = 35;
pub const VIRTIO_F_ORDER_PLATFORM: u32 = 36;
pub const VIRTIO_F_SR_IOV: u32 = 37;
pub const VIRTIO_F_NOTIFICATION_DATA: u32 = 38;
pub const VIRTIO_F_NOTIF_CONFIG_DATA: u32 = 39;
pub const VIRTIO_F_RING_RESET: u32 = 40;
pub const VIRTIO_F_ADMIN_VQ: u32 = 41;
pub const VIRTIO_MSG_DEVICE_INFO: u32 = 2;
pub const VIRTIO_MSG_GET_DEV_FEATURES: u32 = 3;
pub const VIRTIO_MSG_SET_DRV_FEATURES: u32 = 4;
pub const VIRTIO_MSG_GET_CONFIG: u32 = 5;
pub const VIRTIO_MSG_SET_CONFIG: u32 = 6;
pub const VIRTIO_MSG_GET_DEVICE_STATUS: u32 = 7;
pub const VIRTIO_MSG_SET_DEVICE_STATUS: u32 = 8;
pub const VIRTIO_MSG_GET_VQUEUE: u32 = 9;
pub const VIRTIO_MSG_SET_VQUEUE: u32 = 10;
pub const VIRTIO_MSG_RESET_VQUEUE: u32 = 11;
pub const VIRTIO_MSG_GET_SHM: u32 = 12;
pub const VIRTIO_MSG_EVENT_CONFIG: u32 = 64;
pub const VIRTIO_MSG_EVENT_AVAIL: u32 = 65;
pub const VIRTIO_MSG_EVENT_USED: u32 = 66;
pub const VIRTIO_MSG_MAX: u32 = 66;
pub const VIRTIO_MSG_MIN_SIZE: u32 = 50;
pub const VIRTIO_MSG_MAX_SIZE: u32 = 65536;
pub const VIRTIO_MSG_REVISION_1: u32 = 1;
pub const VIRTIO_MSG_EVENT_AVAIL_WRAP_SHIFT: u32 = 31;
pub const VIRTIO_MSG_TYPE_REQUEST: u32 = 0;
pub const VIRTIO_MSG_TYPE_RESPONSE: u32 = 1;
pub const VIRTIO_MSG_TYPE_TRANSPORT: u32 = 0;
pub const VIRTIO_MSG_TYPE_BUS: u32 = 2;
pub const VIRTIO_MSG_BUS_GET_DEVICES: u32 = 2;
pub const VIRTIO_MSG_BUS_PING: u32 = 3;
pub const VIRTIO_MSG_BUS_EVENT_DEVICE: u32 = 64;
pub const VIRTIO_MSG_BUS_EVENT_DEV_STATE_READY: u32 = 1;
pub const VIRTIO_MSG_BUS_EVENT_DEV_STATE_REMOVED: u32 = 2;
pub const VIRTIO_MSG_FFA_BUS_VERSION: u32 = 128;
pub const VIRTIO_MSG_FFA_BUS_AREA_SHARE: u32 = 129;
pub const VIRTIO_MSG_FFA_BUS_AREA_UNSHARE: u32 = 130;
pub const VIRTIO_MSG_FFA_BUS_RESET: u32 = 131;
pub const VIRTIO_MSG_FFA_BUS_EVENT_POLL: u32 = 132;
pub const VIRTIO_MSG_FFA_BUS_EVENT_CONFIGURE: u32 = 133;
pub const VIRTIO_MSG_FFA_BUS_FIFO_CONFIGURE: u32 = 134;
pub const VIRTIO_MSG_FFA_BUS_ERROR: u32 = 135;
pub const VIRTIO_MSG_FFA_BUS_AREA_RELEASE: u32 = 192;
pub const VIRTIO_MSG_FEATURES: u32 = 0;
pub const VIRTIO_MSG_FFA_BUS_MSG_SIZE: u32 = 50;
pub const VIRTIO_MSG_FFA_BUS_MSG_MAX_SIZE: u32 = 104;
pub const VIRTIO_MSG_FFA_FEATURE_DIRECT_MSG_RX_SUPP: u32 = 1;
pub const VIRTIO_MSG_FFA_FEATURE_DIRECT_MSG_TX_SUPP: u32 = 2;
pub const VIRTIO_MSG_FFA_FEATURE_INDIRECT_MSG_RX_SUPP: u32 = 4;
pub const VIRTIO_MSG_FFA_FEATURE_INDIRECT_MSG_TX_SUPP: u32 = 8;
pub const VIRTIO_MSG_FFA_FEATURE_NOTIFICATION_RX_SUPP: u32 = 16;
pub const VIRTIO_MSG_FFA_FEATURE_NOTIFICATION_TX_SUPP: u32 = 32;
pub const VIRTIO_MSG_FFA_FEATURE_FIFO_TX_RX_SUPP: u32 = 64;
pub const VIRTIO_MSG_FFA_FEATURE_DIRECT_MSG_SUPP: u32 = 3;
pub const VIRTIO_MSG_FFA_FEATURE_INDIRECT_MSG_SUPP: u32 = 12;
pub const VIRTIO_MSG_FFA_FEATURE_BOTH_SUPP: u32 = 15;
pub const VIRTIO_MSG_FFA_AREA_ID_MAX: u32 = 65535;
pub const VIRTIO_MSG_FFA_AREA_ID_OFFSET: u32 = 48;
pub const VIRTIO_MSG_FFA_EVENT_DELIVERY_TYPE_POLL: u32 = 0;
pub const VIRTIO_MSG_FFA_EVENT_DELIVERY_TYPE_NOTIF: u32 = 1;
pub const VIRTIO_MSG_FFA_EVENT_DELIVERY_TYPE_INDIRECT: u32 = 2;
pub const VIRTIO_MSG_FFA_EVENT_DELIVERY_TYPE_FIFO: u32 = 3;
pub const VIRTIO_MSG_FFA_RESULT_OK: u32 = 0;
pub const VIRTIO_MSG_FFA_RESULT_ERROR: u32 = 1;
pub const VIRTIO_MSG_FFA_RESULT_BUSY: u32 = 2;
pub type __u8 = u8;
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct get_device_info_resp {
    pub device_id: u32,
    pub vendor_id: u32,
    pub num_feature_bits: u32,
    pub config_size: u32,
    pub max_vq_count: u32,
    pub admin_vq_start_idx: u16,
    pub admin_vq_count: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_device_info_resp"][::core::mem::size_of::<get_device_info_resp>() - 24usize];
    ["Alignment of get_device_info_resp"][::core::mem::align_of::<get_device_info_resp>() - 1usize];
    ["Offset of field: get_device_info_resp::device_id"]
        [::core::mem::offset_of!(get_device_info_resp, device_id) - 0usize];
    ["Offset of field: get_device_info_resp::vendor_id"]
        [::core::mem::offset_of!(get_device_info_resp, vendor_id) - 4usize];
    ["Offset of field: get_device_info_resp::num_feature_bits"]
        [::core::mem::offset_of!(get_device_info_resp, num_feature_bits) - 8usize];
    ["Offset of field: get_device_info_resp::config_size"]
        [::core::mem::offset_of!(get_device_info_resp, config_size) - 12usize];
    ["Offset of field: get_device_info_resp::max_vq_count"]
        [::core::mem::offset_of!(get_device_info_resp, max_vq_count) - 16usize];
    ["Offset of field: get_device_info_resp::admin_vq_start_idx"]
        [::core::mem::offset_of!(get_device_info_resp, admin_vq_start_idx) - 20usize];
    ["Offset of field: get_device_info_resp::admin_vq_count"]
        [::core::mem::offset_of!(get_device_info_resp, admin_vq_count) - 22usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct get_features {
    pub index: u32,
    pub num: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_features"][::core::mem::size_of::<get_features>() - 8usize];
    ["Alignment of get_features"][::core::mem::align_of::<get_features>() - 1usize];
    ["Offset of field: get_features::index"][::core::mem::offset_of!(get_features, index) - 0usize];
    ["Offset of field: get_features::num"][::core::mem::offset_of!(get_features, num) - 4usize];
};
#[repr(C, packed)]
#[derive(Default)]
pub struct get_features_resp {
    pub index: u32,
    pub num: u32,
    pub features: __IncompleteArrayField<__u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_features_resp"][::core::mem::size_of::<get_features_resp>() - 8usize];
    ["Alignment of get_features_resp"][::core::mem::align_of::<get_features_resp>() - 1usize];
    ["Offset of field: get_features_resp::index"]
        [::core::mem::offset_of!(get_features_resp, index) - 0usize];
    ["Offset of field: get_features_resp::num"]
        [::core::mem::offset_of!(get_features_resp, num) - 4usize];
    ["Offset of field: get_features_resp::features"]
        [::core::mem::offset_of!(get_features_resp, features) - 8usize];
};
#[repr(C, packed)]
#[derive(Default)]
pub struct set_features {
    pub index: u32,
    pub num: u32,
    pub features: __IncompleteArrayField<__u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_features"][::core::mem::size_of::<set_features>() - 8usize];
    ["Alignment of set_features"][::core::mem::align_of::<set_features>() - 1usize];
    ["Offset of field: set_features::index"][::core::mem::offset_of!(set_features, index) - 0usize];
    ["Offset of field: set_features::num"][::core::mem::offset_of!(set_features, num) - 4usize];
    ["Offset of field: set_features::features"]
        [::core::mem::offset_of!(set_features, features) - 8usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct get_config {
    pub offset: u32,
    pub size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_config"][::core::mem::size_of::<get_config>() - 8usize];
    ["Alignment of get_config"][::core::mem::align_of::<get_config>() - 1usize];
    ["Offset of field: get_config::offset"][::core::mem::offset_of!(get_config, offset) - 0usize];
    ["Offset of field: get_config::size"][::core::mem::offset_of!(get_config, size) - 4usize];
};
#[repr(C, packed)]
#[derive(Default)]
pub struct get_config_resp {
    pub generation: u32,
    pub offset: u32,
    pub size: u32,
    pub config: __IncompleteArrayField<__u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_config_resp"][::core::mem::size_of::<get_config_resp>() - 12usize];
    ["Alignment of get_config_resp"][::core::mem::align_of::<get_config_resp>() - 1usize];
    ["Offset of field: get_config_resp::generation"]
        [::core::mem::offset_of!(get_config_resp, generation) - 0usize];
    ["Offset of field: get_config_resp::offset"]
        [::core::mem::offset_of!(get_config_resp, offset) - 4usize];
    ["Offset of field: get_config_resp::size"]
        [::core::mem::offset_of!(get_config_resp, size) - 8usize];
    ["Offset of field: get_config_resp::config"]
        [::core::mem::offset_of!(get_config_resp, config) - 12usize];
};
#[repr(C, packed)]
#[derive(Default)]
pub struct set_config {
    pub generation: u32,
    pub offset: u32,
    pub size: u32,
    pub config: __IncompleteArrayField<__u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_config"][::core::mem::size_of::<set_config>() - 12usize];
    ["Alignment of set_config"][::core::mem::align_of::<set_config>() - 1usize];
    ["Offset of field: set_config::generation"]
        [::core::mem::offset_of!(set_config, generation) - 0usize];
    ["Offset of field: set_config::offset"][::core::mem::offset_of!(set_config, offset) - 4usize];
    ["Offset of field: set_config::size"][::core::mem::offset_of!(set_config, size) - 8usize];
    ["Offset of field: set_config::config"][::core::mem::offset_of!(set_config, config) - 12usize];
};
#[repr(C, packed)]
#[derive(Default)]
pub struct set_config_resp {
    pub generation: u32,
    pub offset: u32,
    pub size: u32,
    pub config: __IncompleteArrayField<__u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_config_resp"][::core::mem::size_of::<set_config_resp>() - 12usize];
    ["Alignment of set_config_resp"][::core::mem::align_of::<set_config_resp>() - 1usize];
    ["Offset of field: set_config_resp::generation"]
        [::core::mem::offset_of!(set_config_resp, generation) - 0usize];
    ["Offset of field: set_config_resp::offset"]
        [::core::mem::offset_of!(set_config_resp, offset) - 4usize];
    ["Offset of field: set_config_resp::size"]
        [::core::mem::offset_of!(set_config_resp, size) - 8usize];
    ["Offset of field: set_config_resp::config"]
        [::core::mem::offset_of!(set_config_resp, config) - 12usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct get_device_status_resp {
    pub status: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_device_status_resp"][::core::mem::size_of::<get_device_status_resp>() - 4usize];
    ["Alignment of get_device_status_resp"]
        [::core::mem::align_of::<get_device_status_resp>() - 1usize];
    ["Offset of field: get_device_status_resp::status"]
        [::core::mem::offset_of!(get_device_status_resp, status) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct set_device_status {
    pub status: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_device_status"][::core::mem::size_of::<set_device_status>() - 4usize];
    ["Alignment of set_device_status"][::core::mem::align_of::<set_device_status>() - 1usize];
    ["Offset of field: set_device_status::status"]
        [::core::mem::offset_of!(set_device_status, status) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct set_device_status_resp {
    pub status: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_device_status_resp"][::core::mem::size_of::<set_device_status_resp>() - 4usize];
    ["Alignment of set_device_status_resp"]
        [::core::mem::align_of::<set_device_status_resp>() - 1usize];
    ["Offset of field: set_device_status_resp::status"]
        [::core::mem::offset_of!(set_device_status_resp, status) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct get_vqueue {
    pub index: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_vqueue"][::core::mem::size_of::<get_vqueue>() - 4usize];
    ["Alignment of get_vqueue"][::core::mem::align_of::<get_vqueue>() - 1usize];
    ["Offset of field: get_vqueue::index"][::core::mem::offset_of!(get_vqueue, index) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct get_vqueue_resp {
    pub index: u32,
    pub max_size: u32,
    pub size: u32,
    pub reserved: u32,
    pub descriptor_addr: u64,
    pub driver_addr: u64,
    pub device_addr: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_vqueue_resp"][::core::mem::size_of::<get_vqueue_resp>() - 40usize];
    ["Alignment of get_vqueue_resp"][::core::mem::align_of::<get_vqueue_resp>() - 1usize];
    ["Offset of field: get_vqueue_resp::index"]
        [::core::mem::offset_of!(get_vqueue_resp, index) - 0usize];
    ["Offset of field: get_vqueue_resp::max_size"]
        [::core::mem::offset_of!(get_vqueue_resp, max_size) - 4usize];
    ["Offset of field: get_vqueue_resp::size"]
        [::core::mem::offset_of!(get_vqueue_resp, size) - 8usize];
    ["Offset of field: get_vqueue_resp::reserved"]
        [::core::mem::offset_of!(get_vqueue_resp, reserved) - 12usize];
    ["Offset of field: get_vqueue_resp::descriptor_addr"]
        [::core::mem::offset_of!(get_vqueue_resp, descriptor_addr) - 16usize];
    ["Offset of field: get_vqueue_resp::driver_addr"]
        [::core::mem::offset_of!(get_vqueue_resp, driver_addr) - 24usize];
    ["Offset of field: get_vqueue_resp::device_addr"]
        [::core::mem::offset_of!(get_vqueue_resp, device_addr) - 32usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct set_vqueue {
    pub index: u32,
    pub unused: u32,
    pub size: u32,
    pub reserved: u32,
    pub descriptor_addr: u64,
    pub driver_addr: u64,
    pub device_addr: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_vqueue"][::core::mem::size_of::<set_vqueue>() - 40usize];
    ["Alignment of set_vqueue"][::core::mem::align_of::<set_vqueue>() - 1usize];
    ["Offset of field: set_vqueue::index"][::core::mem::offset_of!(set_vqueue, index) - 0usize];
    ["Offset of field: set_vqueue::unused"][::core::mem::offset_of!(set_vqueue, unused) - 4usize];
    ["Offset of field: set_vqueue::size"][::core::mem::offset_of!(set_vqueue, size) - 8usize];
    ["Offset of field: set_vqueue::reserved"]
        [::core::mem::offset_of!(set_vqueue, reserved) - 12usize];
    ["Offset of field: set_vqueue::descriptor_addr"]
        [::core::mem::offset_of!(set_vqueue, descriptor_addr) - 16usize];
    ["Offset of field: set_vqueue::driver_addr"]
        [::core::mem::offset_of!(set_vqueue, driver_addr) - 24usize];
    ["Offset of field: set_vqueue::device_addr"]
        [::core::mem::offset_of!(set_vqueue, device_addr) - 32usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct reset_vqueue {
    pub index: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of reset_vqueue"][::core::mem::size_of::<reset_vqueue>() - 4usize];
    ["Alignment of reset_vqueue"][::core::mem::align_of::<reset_vqueue>() - 1usize];
    ["Offset of field: reset_vqueue::index"][::core::mem::offset_of!(reset_vqueue, index) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct get_shm {
    pub index: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_shm"][::core::mem::size_of::<get_shm>() - 4usize];
    ["Alignment of get_shm"][::core::mem::align_of::<get_shm>() - 1usize];
    ["Offset of field: get_shm::index"][::core::mem::offset_of!(get_shm, index) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct get_shm_resp {
    pub index: u32,
    pub count: u32,
    pub addr: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of get_shm_resp"][::core::mem::size_of::<get_shm_resp>() - 12usize];
    ["Alignment of get_shm_resp"][::core::mem::align_of::<get_shm_resp>() - 1usize];
    ["Offset of field: get_shm_resp::index"][::core::mem::offset_of!(get_shm_resp, index) - 0usize];
    ["Offset of field: get_shm_resp::count"][::core::mem::offset_of!(get_shm_resp, count) - 4usize];
    ["Offset of field: get_shm_resp::addr"][::core::mem::offset_of!(get_shm_resp, addr) - 8usize];
};
#[repr(C, packed)]
#[derive(Default)]
pub struct event_config {
    pub status: u32,
    pub generation: u32,
    pub offset: u32,
    pub size: u32,
    pub config: __IncompleteArrayField<__u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of event_config"][::core::mem::size_of::<event_config>() - 16usize];
    ["Alignment of event_config"][::core::mem::align_of::<event_config>() - 1usize];
    ["Offset of field: event_config::status"]
        [::core::mem::offset_of!(event_config, status) - 0usize];
    ["Offset of field: event_config::generation"]
        [::core::mem::offset_of!(event_config, generation) - 4usize];
    ["Offset of field: event_config::offset"]
        [::core::mem::offset_of!(event_config, offset) - 8usize];
    ["Offset of field: event_config::size"][::core::mem::offset_of!(event_config, size) - 12usize];
    ["Offset of field: event_config::config"]
        [::core::mem::offset_of!(event_config, config) - 16usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct event_avail {
    pub index: u32,
    pub next_offset_wrap: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of event_avail"][::core::mem::size_of::<event_avail>() - 8usize];
    ["Alignment of event_avail"][::core::mem::align_of::<event_avail>() - 1usize];
    ["Offset of field: event_avail::index"][::core::mem::offset_of!(event_avail, index) - 0usize];
    ["Offset of field: event_avail::next_offset_wrap"]
        [::core::mem::offset_of!(event_avail, next_offset_wrap) - 4usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct event_used {
    pub index: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of event_used"][::core::mem::size_of::<event_used>() - 4usize];
    ["Alignment of event_used"][::core::mem::align_of::<event_used>() - 1usize];
    ["Offset of field: event_used::index"][::core::mem::offset_of!(event_used, index) - 0usize];
};
#[repr(C, packed)]
#[derive(Default)]
pub struct virtio_msg {
    pub type_: __u8,
    pub msg_id: __u8,
    pub dev_id: u16,
    pub token: u16,
    pub msg_size: u16,
    pub payload: __IncompleteArrayField<__u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virtio_msg"][::core::mem::size_of::<virtio_msg>() - 8usize];
    ["Alignment of virtio_msg"][::core::mem::align_of::<virtio_msg>() - 1usize];
    ["Offset of field: virtio_msg::type_"][::core::mem::offset_of!(virtio_msg, type_) - 0usize];
    ["Offset of field: virtio_msg::msg_id"][::core::mem::offset_of!(virtio_msg, msg_id) - 1usize];
    ["Offset of field: virtio_msg::dev_id"][::core::mem::offset_of!(virtio_msg, dev_id) - 2usize];
    ["Offset of field: virtio_msg::token"][::core::mem::offset_of!(virtio_msg, token) - 4usize];
    ["Offset of field: virtio_msg::msg_size"]
        [::core::mem::offset_of!(virtio_msg, msg_size) - 6usize];
    ["Offset of field: virtio_msg::payload"][::core::mem::offset_of!(virtio_msg, payload) - 8usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_get_devices {
    pub offset: u16,
    pub num: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_get_devices"][::core::mem::size_of::<bus_get_devices>() - 4usize];
    ["Alignment of bus_get_devices"][::core::mem::align_of::<bus_get_devices>() - 1usize];
    ["Offset of field: bus_get_devices::offset"]
        [::core::mem::offset_of!(bus_get_devices, offset) - 0usize];
    ["Offset of field: bus_get_devices::num"]
        [::core::mem::offset_of!(bus_get_devices, num) - 2usize];
};
#[repr(C, packed)]
#[derive(Default)]
pub struct bus_get_devices_resp {
    pub offset: u16,
    pub num: u16,
    pub next_offset: u16,
    pub devices: __IncompleteArrayField<__u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_get_devices_resp"][::core::mem::size_of::<bus_get_devices_resp>() - 6usize];
    ["Alignment of bus_get_devices_resp"][::core::mem::align_of::<bus_get_devices_resp>() - 1usize];
    ["Offset of field: bus_get_devices_resp::offset"]
        [::core::mem::offset_of!(bus_get_devices_resp, offset) - 0usize];
    ["Offset of field: bus_get_devices_resp::num"]
        [::core::mem::offset_of!(bus_get_devices_resp, num) - 2usize];
    ["Offset of field: bus_get_devices_resp::next_offset"]
        [::core::mem::offset_of!(bus_get_devices_resp, next_offset) - 4usize];
    ["Offset of field: bus_get_devices_resp::devices"]
        [::core::mem::offset_of!(bus_get_devices_resp, devices) - 6usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_event_device {
    pub dev_num: u16,
    pub dev_state: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_event_device"][::core::mem::size_of::<bus_event_device>() - 4usize];
    ["Alignment of bus_event_device"][::core::mem::align_of::<bus_event_device>() - 1usize];
    ["Offset of field: bus_event_device::dev_num"]
        [::core::mem::offset_of!(bus_event_device, dev_num) - 0usize];
    ["Offset of field: bus_event_device::dev_state"]
        [::core::mem::offset_of!(bus_event_device, dev_state) - 2usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_ping {
    pub data: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_ping"][::core::mem::size_of::<bus_ping>() - 4usize];
    ["Alignment of bus_ping"][::core::mem::align_of::<bus_ping>() - 1usize];
    ["Offset of field: bus_ping::data"][::core::mem::offset_of!(bus_ping, data) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_ping_resp {
    pub data: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_ping_resp"][::core::mem::size_of::<bus_ping_resp>() - 4usize];
    ["Alignment of bus_ping_resp"][::core::mem::align_of::<bus_ping_resp>() - 1usize];
    ["Offset of field: bus_ping_resp::data"][::core::mem::offset_of!(bus_ping_resp, data) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_ffa_version {
    pub bus_version: u32,
    pub transport_revision: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_ffa_version"][::core::mem::size_of::<bus_ffa_version>() - 8usize];
    ["Alignment of bus_ffa_version"][::core::mem::align_of::<bus_ffa_version>() - 1usize];
    ["Offset of field: bus_ffa_version::bus_version"]
        [::core::mem::offset_of!(bus_ffa_version, bus_version) - 0usize];
    ["Offset of field: bus_ffa_version::transport_revision"]
        [::core::mem::offset_of!(bus_ffa_version, transport_revision) - 4usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_ffa_version_resp {
    pub bus_version: u32,
    pub transport_revision: u32,
    pub transport_features: u32,
    pub bus_features: u32,
    pub area_num: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_ffa_version_resp"][::core::mem::size_of::<bus_ffa_version_resp>() - 18usize];
    ["Alignment of bus_ffa_version_resp"][::core::mem::align_of::<bus_ffa_version_resp>() - 1usize];
    ["Offset of field: bus_ffa_version_resp::bus_version"]
        [::core::mem::offset_of!(bus_ffa_version_resp, bus_version) - 0usize];
    ["Offset of field: bus_ffa_version_resp::transport_revision"]
        [::core::mem::offset_of!(bus_ffa_version_resp, transport_revision) - 4usize];
    ["Offset of field: bus_ffa_version_resp::transport_features"]
        [::core::mem::offset_of!(bus_ffa_version_resp, transport_features) - 8usize];
    ["Offset of field: bus_ffa_version_resp::bus_features"]
        [::core::mem::offset_of!(bus_ffa_version_resp, bus_features) - 12usize];
    ["Offset of field: bus_ffa_version_resp::area_num"]
        [::core::mem::offset_of!(bus_ffa_version_resp, area_num) - 16usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_area_share {
    pub area_id: u16,
    pub mem_handle: u64,
    pub tag: u64,
    pub count: u32,
    pub attr: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_area_share"][::core::mem::size_of::<bus_area_share>() - 26usize];
    ["Alignment of bus_area_share"][::core::mem::align_of::<bus_area_share>() - 1usize];
    ["Offset of field: bus_area_share::area_id"]
        [::core::mem::offset_of!(bus_area_share, area_id) - 0usize];
    ["Offset of field: bus_area_share::mem_handle"]
        [::core::mem::offset_of!(bus_area_share, mem_handle) - 2usize];
    ["Offset of field: bus_area_share::tag"]
        [::core::mem::offset_of!(bus_area_share, tag) - 10usize];
    ["Offset of field: bus_area_share::count"]
        [::core::mem::offset_of!(bus_area_share, count) - 18usize];
    ["Offset of field: bus_area_share::attr"]
        [::core::mem::offset_of!(bus_area_share, attr) - 22usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_area_share_resp {
    pub area_id: u16,
    pub result: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_area_share_resp"][::core::mem::size_of::<bus_area_share_resp>() - 4usize];
    ["Alignment of bus_area_share_resp"][::core::mem::align_of::<bus_area_share_resp>() - 1usize];
    ["Offset of field: bus_area_share_resp::area_id"]
        [::core::mem::offset_of!(bus_area_share_resp, area_id) - 0usize];
    ["Offset of field: bus_area_share_resp::result"]
        [::core::mem::offset_of!(bus_area_share_resp, result) - 2usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_area_unshare {
    pub area_id: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_area_unshare"][::core::mem::size_of::<bus_area_unshare>() - 2usize];
    ["Alignment of bus_area_unshare"][::core::mem::align_of::<bus_area_unshare>() - 1usize];
    ["Offset of field: bus_area_unshare::area_id"]
        [::core::mem::offset_of!(bus_area_unshare, area_id) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_area_unshare_resp {
    pub area_id: u16,
    pub result: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_area_unshare_resp"][::core::mem::size_of::<bus_area_unshare_resp>() - 4usize];
    ["Alignment of bus_area_unshare_resp"]
        [::core::mem::align_of::<bus_area_unshare_resp>() - 1usize];
    ["Offset of field: bus_area_unshare_resp::area_id"]
        [::core::mem::offset_of!(bus_area_unshare_resp, area_id) - 0usize];
    ["Offset of field: bus_area_unshare_resp::result"]
        [::core::mem::offset_of!(bus_area_unshare_resp, result) - 2usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_reset_resp {
    pub result: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_reset_resp"][::core::mem::size_of::<bus_reset_resp>() - 2usize];
    ["Alignment of bus_reset_resp"][::core::mem::align_of::<bus_reset_resp>() - 1usize];
    ["Offset of field: bus_reset_resp::result"]
        [::core::mem::offset_of!(bus_reset_resp, result) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_event_configure {
    pub type_: __u8,
    pub reserved: __u8,
    pub notify_id: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_event_configure"][::core::mem::size_of::<bus_event_configure>() - 4usize];
    ["Alignment of bus_event_configure"][::core::mem::align_of::<bus_event_configure>() - 1usize];
    ["Offset of field: bus_event_configure::type_"]
        [::core::mem::offset_of!(bus_event_configure, type_) - 0usize];
    ["Offset of field: bus_event_configure::reserved"]
        [::core::mem::offset_of!(bus_event_configure, reserved) - 1usize];
    ["Offset of field: bus_event_configure::notify_id"]
        [::core::mem::offset_of!(bus_event_configure, notify_id) - 2usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_event_configure_resp {
    pub result: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_event_configure_resp"]
        [::core::mem::size_of::<bus_event_configure_resp>() - 2usize];
    ["Alignment of bus_event_configure_resp"]
        [::core::mem::align_of::<bus_event_configure_resp>() - 1usize];
    ["Offset of field: bus_event_configure_resp::result"]
        [::core::mem::offset_of!(bus_event_configure_resp, result) - 0usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_fifo_configure {
    pub mem_handle: u64,
    pub page_count: u16,
    pub notify_id: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_fifo_configure"][::core::mem::size_of::<bus_fifo_configure>() - 12usize];
    ["Alignment of bus_fifo_configure"][::core::mem::align_of::<bus_fifo_configure>() - 1usize];
    ["Offset of field: bus_fifo_configure::mem_handle"]
        [::core::mem::offset_of!(bus_fifo_configure, mem_handle) - 0usize];
    ["Offset of field: bus_fifo_configure::page_count"]
        [::core::mem::offset_of!(bus_fifo_configure, page_count) - 8usize];
    ["Offset of field: bus_fifo_configure::notify_id"]
        [::core::mem::offset_of!(bus_fifo_configure, notify_id) - 10usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_fifo_configure_resp {
    pub result: u16,
    pub notify_id: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_fifo_configure_resp"][::core::mem::size_of::<bus_fifo_configure_resp>() - 4usize];
    ["Alignment of bus_fifo_configure_resp"]
        [::core::mem::align_of::<bus_fifo_configure_resp>() - 1usize];
    ["Offset of field: bus_fifo_configure_resp::result"]
        [::core::mem::offset_of!(bus_fifo_configure_resp, result) - 0usize];
    ["Offset of field: bus_fifo_configure_resp::notify_id"]
        [::core::mem::offset_of!(bus_fifo_configure_resp, notify_id) - 2usize];
};
#[repr(C, packed)]
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    zerocopy :: Immutable,
    zerocopy :: FromBytes,
    zerocopy :: IntoBytes,
    zerocopy :: KnownLayout,
)]
pub struct bus_area_release {
    pub area_id: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of bus_area_release"][::core::mem::size_of::<bus_area_release>() - 2usize];
    ["Alignment of bus_area_release"][::core::mem::align_of::<bus_area_release>() - 1usize];
    ["Offset of field: bus_area_release::area_id"]
        [::core::mem::offset_of!(bus_area_release, area_id) - 0usize];
};
