#![no_std]
#![allow(non_camel_case_types)]
#![feature(cfg_version)]
// C string byte counts were stabilized in Rust 1.79
#![cfg_attr(not(version("1.79")), feature(cstr_count_bytes))]
// C string literals were stabilized in Rust 1.77
#![cfg_attr(not(version("1.77")), feature(c_str_literals))]
// unsigned_is_multiple_of feature was stabilized in Rust 1.87
#![cfg_attr(not(version("1.87")), feature(unsigned_is_multiple_of))]

mod err;
mod hal;
#[cfg(target_arch = "aarch64")]
#[cfg(any(feature = "virtio_msg_device", feature = "virtio_msg_driver"))]
mod msg;
mod pci;
mod vsock;

// TODO: Follow the normal bindgen pattern once we find a suitable location for
// the header files that the virtio-msg bindings were generated from. Current
// bindings were generated by building generic-arm64-virt-test-debug with
// aosp/3390803/25 applied and used prebuilt bindgen 0.69.5.
#[allow(clippy::upper_case_acronyms)]
#[allow(unused)]
#[allow(non_camel_case_types)]
#[allow(non_upper_case_globals)]
#[rustfmt::skip]
#[path = "bindings.rs"]
mod sys;

#[allow(clippy::upper_case_acronyms)]
#[allow(unused)]
#[allow(non_camel_case_types)]
#[allow(non_upper_case_globals)]
#[rustfmt::skip]
#[path = "new_bindings.rs"]
mod sys_dev2;

pub use err::Error;
pub use pci::pci_init_mmio;

// FF-A partitions use 16-bit IDs
type FFAClientId = u16;

// Vsock devices do not need bits above 64
#[allow(unused)]
type VsockVirtioFeatures = u64;
